const urlMapping = {
    device_data_insert: '/data/device/insert',
    device_data_delete: '/data/device/delete',
    device_data_detail: '/data/device/detail',
    device_data_update: '/data/device/update',
    device_view_list: '/view/device/list',
    device_view_insert: '/view/device/insert',
    device_view_detail: '/view/device/detail',

    device_model_data_combo: '/data/device-model/combo',
    device_model_data_update: '/data/device-model/update',
    device_model_data_detail: '/data/device-model/detail',
    device_model_data_insert: '/data/device-model/insert',
    device_model_data_delete: '/data/device-model/delete',
    device_model_view_list: '/view/device-model/list',
    device_model_view_insert: '/view/device-model/insert',
    device_model_view_detail: '/view/device-model/detail',

    hndset_data_page_usable: '/data/hndset/page/usable',
    hndset_data_update: '/data/hndset/update',
    hndset_data_detail: '/data/hndset/detail',
    hndset_data_insert: '/data/hndset/insert',
    hndset_data_insert_open_hist: '/data/hndset/insert/open-hist',
    hndset_data_delete: '/data/hndset/delete',
    hndset_view_list:   '/view/hndset/list',
    hndset_view_insert: '/view/hndset/insert',
    hndset_view_detail: '/view/hndset/detail',

    install_data_request: '/data/install/request',
    install_data_update: '/data/install/update',
    install_data_detail: '/data/install/detail',
    install_data_insert: '/data/install/insert',
    install_data_delete: '/data/install/delete',
    install_view_list:   '/view/install/list',
    install_view_insert: '/view/install/insert',
    install_view_detail: '/view/install/detail',

    vehicle_data_page_usable: '/data/vehicle/page/usable',
    vehicle_data_update: '/data/vehicle/update',
    vehicle_data_detail: '/data/vehicle/detail',
    vehicle_data_insert: '/data/vehicle/insert',
    vehicle_data_delete: '/data/vehicle/delete',
    vehicle_view_list:   '/view/vehicle/list',
    vehicle_view_insert: '/view/vehicle/insert',
    vehicle_view_detail: '/view/vehicle/detail',

    device_stock_data_page_device_model_detail : '/data/device-stock/page/device-model/detail',
    device_stock_data_update: '/data/device-stock/update',
    device_stock_data_detail: '/data/device-stock/detail',
    device_stock_data_insert: '/data/device-stock/insert',
    device_stock_data_insert_many: '/data/device-stock/insert/many',
    device_stock_data_exist: '/data/device-stock/exist',
    device_stock_data_delete: '/data/device-stock/delete',
    device_stock_view_list:   '/view/device-stock/list',
    device_stock_view_insert: '/view/device-stock/insert',
    device_stock_view_detail: '/view/device-stock/detail',

    common_data_mfg_list: '/data/common/mfg-list',
    common_data_cmpn: '/data/common/cmpn',

    code_hndset_mount_status_list: '/data/code/hndset-mnt-st-list',
    code_hndset_open_status_list : '/data/code/hndset-open-st-list',
    code_hndset_carrier_list: '/data/code/hndset-carrier-list',
    code_vehicle_type_list : '/data/code/vehicle-tp-list'
}